---
- name: Ensure Prometheus configuration file is applied
  ansible.builtin.template:
    src: prometheus.yaml.j2
    dest: "{{ prometheus_config_path }}"
    owner: root
    group: prometheus
    mode: '0640'
  notify: Reload Prometheus

- name: Ensure Prometheus Web configuration is applied
  ansible.builtin.template:
    src: web.yaml.j2
    dest: "{{ prometheus_web_config_path }}"
    owner: root
    group: prometheus
    mode: '0640'
  notify: Reload Prometheus

- name: Ensure Prometheus alerting rules are configured
  ansible.builtin.template:
    src: alert_rule.j2
    dest: "{{ prometheus_config_dir }}/rules/{{ rule.group }}.rules"
    owner: root
    group: prometheus
    mode: '0644'
  with_items: "{{ prometheus_alerting_rules }}"
  loop_control:
    loop_var: rule
  notify: Reload Prometheus

- name: Ensure Prometheus non-managed alerting files are deployed
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules"
    owner: root
    group: prometheus
    mode: '0644'
  with_fileglob: "{{ prometheus_alerting_rules_files }}"
  notify: Reload Prometheus

- name: Ensure Prometheus custom environment file is applied
  ansible.builtin.template:
    src: env.j2
    dest: "{{ prometheus_env_file }}"
    owner: root
    group: root
    mode: '0644'
