---
- name: Ensure Prometheus directories hierarchy is created
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
  - { path: "{{ prometheus_data_dir }}", owner: prometheus, group: prometheus, mode: '0755' }
  - { path: "{{ prometheus_config_dir }}", owner: root, group: prometheus, mode: '0755' }
  - { path: "{{ prometheus_config_dir }}/rules", owner: root, group: prometheus, mode: '0755' }

- name: Check if Prometheus binary is already installed
  ansible.builtin.stat:
    path: "{{ prometheus_install_dir }}/prometheus"
  register: _prometheus_binary

- name: Install Prometheus
  when: not _prometheus_binary.stat.exists or prometheus_binary_update
  block:
    - name: Download Prometheus binary archive
      ansible.builtin.get_url:
        url: "{{ prometheus_binary_archive_url }}"
        dest: "/tmp/prometheus_{{ prometheus_version }}.tar.gz"
        checksum: "sha256:{{ prometheus_binary_archive_checksum }}"
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Prometheus binaries are installed
      ansible.builtin.unarchive:
        src: "/tmp/prometheus_{{ prometheus_version }}.tar.gz"
        dest: "{{ prometheus_install_dir }}"
        include:
          - 'prometheus-{{ prometheus_version }}.linux-amd64/prometheus'
          - 'prometheus-{{ prometheus_version }}.linux-amd64/promtool'
        extra_opts: ['--strip-components=1']
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

    - name: Ensure Prometheus consoles templates are installed
      ansible.builtin.unarchive:
        src: "/tmp/prometheus_{{ prometheus_version }}.tar.gz"
        dest: "{{ prometheus_config_dir }}"
        include:
          - 'prometheus-{{ prometheus_version }}.linux-amd64/consoles'
          - 'prometheus-{{ prometheus_version }}.linux-amd64/console_libraries'
        extra_opts: ['--strip-components=1']
        remote_src: yes
        owner: root
        group: prometheus
        mode: '0644'

    - name: Ensure Prometheus binary archive is purged
      ansible.builtin.file:
        path: "/tmp/prometheus_{{ prometheus_version }}.tar.gz"
        state: absent
