---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Pre-installation system tasks
  ansible.builtin.import_tasks: system.yml

- name: Install Prometheus
  ansible.builtin.import_tasks: install.yml

- name: Configure Prometheus
  ansible.builtin.import_tasks: configure.yml

- name: Manage Prometheus service
  ansible.builtin.import_tasks: service.yml
