---
- name: Restart Prometheus service
  ansible.builtin.systemd:
    name: prometheus.service
    state: restarted
    daemon_reload: yes

- name: Reload Prometheus
  ansible.builtin.systemd:
    name: prometheus.service
    state: reloaded
