---
# -----------------------------------------------------------------------------
# GLOBAL
# -----------------------------------------------------------------------------
prometheus_global_config:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

prometheus_extra_args:
  - '--web.route-prefix=/'
  - '--enable-feature=remote-write-receiver'

# -----------------------------------------------------------------------------
# SCRAPE CONFIGS
# -----------------------------------------------------------------------------
prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']

# -----------------------------------------------------------------------------
# ALERTING
# -----------------------------------------------------------------------------
prometheus_alerting_config:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']

prometheus_alerting_rules:
  - group: molecule
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 5m
      labels:
        severity: page
      annotations:
        summary: "{% raw %}Instance {{ $labels.instance }} down{% endraw %}"
        description: "{% raw %}{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.{% endraw %}"
